name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Accept licenses (1/2)
      run: yes | /usr/local/lib/android/tools/bin/sdkmanager --update
    - name: Accept licenses (2/2)
      run: yes| /usr/local/lib/android/tools/bin/sdkmanager --licenses
    - name: Build with Gradle
      run: ./gradlew build
